# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('display', models.CharField(max_length=45, unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cc',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Schema'),
        ),
    ]
